-- Data migration: translate user-facing text already stored in Spanish into French.
-- Schema is unchanged; only rows are rewritten.

-- ─── 1. Skill categories (global catalog originally seeded in Spanish) ───

-- 1a. If the French row already exists (re-seeded catalog), move the user skills
--     onto it, unless the user already owns the French skill.
UPDATE "user_skills" us
SET "skillCategoryId" = fr."id"
FROM (VALUES
    ('Voz',         'Chant'),
    ('Guitarra',    'Guitare'),
    ('Bajo',        'Basse'),
    ('Batería',     'Batterie'),
    ('Sonido',      'Son'),
    ('Iluminación', 'Éclairage'),
    ('Producción',  'Production'),
    ('Video',       'Vidéo')
  ) AS m(es_name, fr_name)
  JOIN "skill_categories" es ON es."name" = m.es_name
  JOIN "skill_categories" fr ON fr."name" = m.fr_name
WHERE us."skillCategoryId" = es."id"
  AND NOT EXISTS (
    SELECT 1 FROM "user_skills" dup
    WHERE dup."userId" = us."userId" AND dup."skillCategoryId" = fr."id"
  );

-- 1b. Drop the skills that could not be moved because the user already had the French one.
DELETE FROM "user_skills" us
USING (VALUES
    ('Voz',         'Chant'),
    ('Guitarra',    'Guitare'),
    ('Bajo',        'Basse'),
    ('Batería',     'Batterie'),
    ('Sonido',      'Son'),
    ('Iluminación', 'Éclairage'),
    ('Producción',  'Production'),
    ('Video',       'Vidéo')
  ) AS m(es_name, fr_name)
  JOIN "skill_categories" es ON es."name" = m.es_name
  JOIN "skill_categories" fr ON fr."name" = m.fr_name
WHERE us."skillCategoryId" = es."id";

-- 1c. Remove the now-orphan Spanish rows that have a French twin.
DELETE FROM "skill_categories" es
USING (VALUES
    ('Voz',         'Chant'),
    ('Guitarra',    'Guitare'),
    ('Bajo',        'Basse'),
    ('Batería',     'Batterie'),
    ('Sonido',      'Son'),
    ('Iluminación', 'Éclairage'),
    ('Producción',  'Production'),
    ('Video',       'Vidéo')
  ) AS m(es_name, fr_name)
  JOIN "skill_categories" fr ON fr."name" = m.fr_name
WHERE es."name" = m.es_name;

-- 1d. Rename the remaining Spanish rows (no French twin existed).
UPDATE "skill_categories" sc
SET "name" = m.fr_name
FROM (VALUES
    ('Voz',         'Chant'),
    ('Guitarra',    'Guitare'),
    ('Bajo',        'Basse'),
    ('Batería',     'Batterie'),
    ('Sonido',      'Son'),
    ('Iluminación', 'Éclairage'),
    ('Producción',  'Production'),
    ('Video',       'Vidéo')
  ) AS m(es_name, fr_name)
WHERE sc."name" = m.es_name;

-- ─── 2. Notifications (titles and bodies generated by the backend) ───

UPDATE "notifications"
SET "title" = regexp_replace("title", '^Te añadieron al evento: (.*)$', 'Vous avez été ajouté à l''événement : \1')
WHERE "title" LIKE 'Te añadieron al evento: %';

UPDATE "notifications"
SET "body" = regexp_replace("body", '^Tu rol: (.*)$', 'Votre rôle : \1')
WHERE "body" LIKE 'Tu rol: %';

UPDATE "notifications" SET "title" = 'Dépense approuvée' WHERE "title" = 'Gasto aprobado';
UPDATE "notifications" SET "title" = 'Dépense refusée'   WHERE "title" = 'Gasto rechazado';

UPDATE "notifications"
SET "body" = regexp_replace("body", '^(.*) aprobó tu gasto de (.*)$', '\1 a approuvé votre dépense de \2')
WHERE "body" LIKE '% aprobó tu gasto de %';

UPDATE "notifications"
SET "body" = regexp_replace("body", '^(.*) rechazó tu gasto: (.*)$', '\1 a refusé votre dépense : \2')
WHERE "body" LIKE '% rechazó tu gasto: %';

UPDATE "notifications"
SET "body" = regexp_replace("body", '^(.*) rechazó tu gasto$', '\1 a refusé votre dépense')
WHERE "body" LIKE '% rechazó tu gasto';

UPDATE "notifications"
SET "title" = regexp_replace("title", '^Instrumento asignado: (.*)$', 'Instrument attribué : \1')
WHERE "title" LIKE 'Instrumento asignado: %';

UPDATE "notifications"
SET "title" = regexp_replace("title", '^Nuevo mensaje de (.*)$', 'Nouveau message de \1')
WHERE "title" LIKE 'Nuevo mensaje de %';

UPDATE "notifications"
SET "title" = regexp_replace("title", '^Rol actualizado en (.*)$', 'Rôle mis à jour dans \1')
WHERE "title" LIKE 'Rol actualizado en %';

UPDATE "notifications"
SET "body" = regexp_replace("body", '^Tu nuevo rol es: (.*)$', 'Votre nouveau rôle est : \1')
WHERE "body" LIKE 'Tu nuevo rol es: %';

UPDATE "notifications"
SET "title" = regexp_replace("title", '^(.*) se unió a (.*)$', '\1 a rejoint \2')
WHERE "title" LIKE '% se unió a %';

UPDATE "notifications"
SET "title" = regexp_replace("title", '^(.*) te invita a unirte a (.*)$', '\1 vous invite à rejoindre \2')
WHERE "title" LIKE '% te invita a unirte a %';

UPDATE "notifications"
SET "title" = regexp_replace("title", '^(.*) aceptó tu invitación a (.*)$', '\1 a accepté votre invitation à \2')
WHERE "title" LIKE '% aceptó tu invitación a %';

UPDATE "notifications"
SET "title" = regexp_replace("title", '^(.*) rechazó tu invitación a (.*)$', '\1 a refusé votre invitation à \2')
WHERE "title" LIKE '% rechazó tu invitación a %';

-- Anonymous-sender fallbacks embedded in the titles above.
UPDATE "notifications"
SET "title" = replace("title", 'Alguien ', 'Quelqu''un ')
WHERE "title" LIKE 'Alguien %';

UPDATE "notifications"
SET "title" = replace("title", 'de alguien', 'de quelqu''un')
WHERE "title" LIKE '%de alguien%';
